<cfset dtssync=replace(dts,'_i','sync','all')>
<cfset dtssync2=replace(dts,'_i','_a','all')>

<cfquery name="getgsetup" datasource="#dts#">
select ddllocation,voidtransfer,possyncprice,possyncbarcode from gsetup
</cfquery>


<cfloop list="INV,CS" index="i">
<cfquery name="getlist" datasource="#dtssync#">
SELECT refno FROM artran WHERE <cfif i eq "RC">type in ('RC','TR','TRIN','TROU')<cfelse>type = "#i#"</cfif>
and wos_date = "#dateformat(now(),'YYYY-MM-DD')#"
</cfquery>
<cfquery name="getownlist" datasource="#dts#">
SELECT * FROM artran WHERE type = "#i#" and refno not in (<cfqueryparam cfsqltype="cf_sql_varchar" value="#valuelist(getlist.refno)#">)
and wos_date = "#dateformat(now(),'YYYY-MM-DD')#"
<cfif i eq "RC">
AND rem49<>"transfer"
</cfif>
</cfquery>
<cfloop query="getownlist">
<cfquery name="insertintocloud" datasource="#dtssync#">
INSERT IGNORE INTO artran
(
TYPE,
REFNO,
REFNO2,
OLD_REFNO,
REVISION,
TRANCODE,
CUSTNO,
FPERIOD,
WOS_DATE,
DESP,
DESPA,
AGENNO,
AREA,
SOURCE,
JOB,
CURRRATE,
GROSS_BIL,
DISC1_BIL,
DISC2_BIL,
DISC3_BIL,
DISC_BIL,
NET_BIL,
TAX1_BIL,
TAX2_BIL,
TAX3_BIL,
TAX_BIL,
GRAND_BIL,
DEBIT_BIL,
CREDIT_BIL,
INVGROSS,
DISP1,
DISP2,
DISP3,
DISCOUNT1,
DISCOUNT2,
DISCOUNT3,
DISCOUNT,
NET,
TAX1,
TAX2,
TAX3,
TAX,
TAXP1,
TAXP2,
TAXP3,
GRAND,
DEBITAMT,
CREDITAMT,
MC1_BIL,
MC2_BIL,
M_CHARGE1,
M_CHARGE2,
CS_PM_CASH,
CS_PM_CHEQ,
CS_PM_CRCD,
CS_PM_CRC2,
CS_PM_TT,
CS_PM_DBCD,
CS_PM_VOUC,
DEPOSIT,
CS_PM_DEBT,
CS_PM_WHT,
CHECKNO,
IMPSTAGE,
BILLCOST,
BILLSALE,
PAIDAMT,
REFNO3,
AGE,
NOTE,
TERM,
ISCASH,
VAN,
DEL_BY,
URGENCY,
CURRRATE2,
STAXACC,
SUPP1,
SUPP2,
PONO,
DONO,
REM0,
REM1,
REM2,
REM3,
REM4,
REM5,
REM6,
REM7,
REM8,
REM9,
REM10,
REM11,
REM12,
permitno,
FREM0,
FREM1,
FREM2,
FREM3,
FREM4,
FREM5,
FREM6,
FREM7,
FREM8,
FREM9,
COMM1,
COMM2,
COMM3,
COMM4,
ID,
GENERATED,
TOINV,
ORDER_CL,
EXPORTED,

EXPORTED2,

LAST_YEAR,
POSTED,
PRINTED,
LOKSTATUS,
VOID,
NAME,
PHONEA,
PONO2,
DONO2,
CSGTRANS,
TAXINCL,
TABLENO,
CASHIER,
MEMBER,
COUNTER,
TOURGROUP,
TRDATETIME,
TIME,
XTRCOST,
XTRCOST2,
POINT,
USERID,
BPERIOD,
VPERIOD,

CURRCODE,
COMM0,
REM13,
REM14,
MC3_BIL,
MC4_BIL,
MC5_BIL,
MC6_BIL,
MC7_BIL,
M_CHARGE3,
M_CHARGE4,
M_CHARGE5,
M_CHARGE6,
M_CHARGE7,
SPECIAL_ACCOUNT_CODE,
CREATED_BY,
UPDATED_BY,
CREATED_ON,
UPDATED_ON,
consignment,
PACKED,
PACKED_ON,
PACKED_BY,
eInvoice_Submited,
SUBMITED_ON,
PONODATE,
IRAS_POSTED,
voucher,
REM30,
REM31,
REM32,
REM33,
REM34,
REM35,
REM36,
REM37,
REM38,
REM39,
REM40,
REM41,
REM42,
REM43,
REM44,
REM45,
REM46,
REM47,
REM48,
REM49,
multiagent1,
multiagent2,
multiagent3,
multiagent4,
multiagent5,
multiagent6,
multiagent7,
multiagent8,
e_mail,
unlocked,
printstatus,
creditcardtype1,
creditcardtype2,
SONO,
termscondition,
CS_PM_CASHCD,
roundadj
)
VALUES
(
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.TYPE#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REFNO#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REFNO2#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.OLD_REFNO#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REVISION#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.TRANCODE#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.CUSTNO#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.FPERIOD#">,
<cfqueryparam cfsqltype="cf_sql_date" value="#getownlist.WOS_DATE#">,
<cfif getownlist.TYPE eq "CS" or getownlist.TYPE eq "INV">
<cfqueryparam cfsqltype="cf_sql_varchar" value="CASH SALES">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="CASH SALES">,
<cfelse>
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.DESP#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.DESPA#">,
</cfif>
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.AGENNO#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.AREA#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.SOURCE#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.JOB#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.CURRRATE#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.GROSS_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.DISC1_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.DISC2_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.DISC3_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.DISC_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.NET_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.TAX1_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.TAX2_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.TAX3_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.TAX_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.GRAND_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.DEBIT_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.CREDIT_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.INVGROSS#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.DISP1#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.DISP2#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.DISP3#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.DISCOUNT1#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.DISCOUNT2#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.DISCOUNT3#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.DISCOUNT#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.NET#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.TAX1#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.TAX2#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.TAX3#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.TAX#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.TAXP1#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.TAXP2#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.TAXP3#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.GRAND#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.DEBITAMT#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.CREDITAMT#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.MC1_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.MC2_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.M_CHARGE1#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.M_CHARGE2#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.CS_PM_CASH#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.CS_PM_CHEQ#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.CS_PM_CRCD#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.CS_PM_CRC2#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.CS_PM_TT#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.CS_PM_DBCD#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.CS_PM_VOUC#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.DEPOSIT#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.CS_PM_DEBT#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.CS_PM_WHT#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.CHECKNO#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.IMPSTAGE#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.BILLCOST#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.BILLSALE#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.PAIDAMT#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REFNO3#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.AGE#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.NOTE#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.TERM#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.ISCASH#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.VAN#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.DEL_BY#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.URGENCY#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.CURRRATE2#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.STAXACC#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.SUPP1#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.SUPP2#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.PONO#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.DONO#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM0#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM1#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM2#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM3#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM4#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM5#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM6#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM7#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM8#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM9#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM10#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM11#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM12#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.permitno#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.FREM0#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.FREM1#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.FREM2#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.FREM3#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.FREM4#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.FREM5#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.FREM6#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.FREM7#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.FREM8#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.FREM9#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.COMM1#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.COMM2#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.COMM3#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.COMM4#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.ID#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.GENERATED#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.TOINV#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.ORDER_CL#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.EXPORTED#">,

<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.EXPORTED2#">,

<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.LAST_YEAR#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.POSTED#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.PRINTED#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.LOKSTATUS#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.VOID#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.NAME#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.PHONEA#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.PONO2#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.DONO2#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.CSGTRANS#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.TAXINCL#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.TABLENO#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.CASHIER#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.MEMBER#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.COUNTER#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.TOURGROUP#">,
<cfqueryparam cfsqltype="cf_sql_timestamp" value="#getownlist.TRDATETIME#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.TIME#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.XTRCOST#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.XTRCOST2#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.POINT#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.USERID#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.BPERIOD#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.VPERIOD#">,

<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.CURRCODE#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.COMM0#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM13#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM14#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.MC3_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.MC4_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.MC5_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.MC6_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.MC7_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.M_CHARGE3#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.M_CHARGE4#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.M_CHARGE5#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.M_CHARGE6#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.M_CHARGE7#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.SPECIAL_ACCOUNT_CODE#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.CREATED_BY#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.UPDATED_BY#">,
<cfqueryparam cfsqltype="cf_sql_timestamp" value="#getownlist.CREATED_ON#">,
<cfqueryparam cfsqltype="cf_sql_timestamp" value="#getownlist.UPDATED_ON#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.consignment#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.PACKED#">,
<cfqueryparam cfsqltype="cf_sql_timestamp" value="#getownlist.PACKED_ON#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.PACKED_BY#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.eInvoice_Submited#">,
<cfqueryparam cfsqltype="cf_sql_timestamp" value="#getownlist.SUBMITED_ON#">,
<cfqueryparam cfsqltype="cf_sql_date" value="#getownlist.PONODATE#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.IRAS_POSTED#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.voucher#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM30#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM31#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM32#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM33#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM34#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM35#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM36#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM37#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM38#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM39#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM40#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM41#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM42#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM43#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM44#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM45#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM46#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM47#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM48#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.REM49#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.multiagent1#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.multiagent2#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.multiagent3#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.multiagent4#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.multiagent5#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.multiagent6#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.multiagent7#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.multiagent8#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.e_mail#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.unlocked#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.printstatus#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.creditcardtype1#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.creditcardtype2#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.SONO#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.termscondition#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.CS_PM_CASHCD#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getownlist.roundadj#">
)
</cfquery>

<cfquery name="getictran" datasource="#dts#">
SELECT * FROM ictran WHERE type = "#getownlist.type#" and refno = <cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.refno#">
</cfquery>
<cfloop query="getictran">
<cfquery name="insertictran" datasource="#dtssync#">
INSERT IGNORE INTO ictran
(
TYPE,
REFNO,
REFNO2,
TRANCODE,
CUSTNO,
FPERIOD,
WOS_DATE,
CURRRATE,
ITEMCOUNT,
LINECODE,
ITEMNO,
DESP,
DESPA,
AGENNO,
LOCATION,
SOURCE,
JOB,
SIGN,
QTY_BIL,
PRICE_BIL,
UNIT_BIL,
AMT1_BIL,
DISPEC1,
DISPEC2,
DISPEC3,
DISAMT_BIL,
AMT_BIL,
TAXPEC1,
TAXPEC2,
TAXPEC3,
TAXAMT_BIL,
NOTE_A,
IMPSTAGE,
QTY,
PRICE,
UNIT,
AMT1,
DISAMT,
AMT,
TAXAMT,
FACTOR1,
FACTOR2,
DONO,
BREM1,
BREM2,
BREM3,
BREM4,
PACKING,
NOTE1,
NOTE2,
GLTRADAC,
UPDCOST,
GST_ITEM,
TOTALUP,
WITHSN,
NODISPLAY,
GRADE,
PUR_PRICE,
QTY1,
QTY2,
QTY3,
QTY4,
QTY5,
QTY6,
QTY7,
QTY_RET,
TEMPFIGI,
SERCOST,
M_CHARGE1,
M_CHARGE2,
ADTCOST1,
ADTCOST2,
IT_COS,
AV_COST,
BATCHCODE,
POINT,
INV_DISC,
INV_TAX,
SUPP,
EDI_COU1,
WRITEOFF,
TOSHIP,
SHIPPED,
NAME,
DEL_BY,
VAN,
GENERATED,
UD_QTY,
TOINV,
EXPORTED,

EXPORTED2,

BRK_TO,
SV_PART,
LAST_YEAR,
VOID,
SONO,
MC1_BIL,
MC2_BIL,
USERID,
DAMT,
OLDBILL,
WOS_GROUP,
CATEGORY,
AREA,
SHELF,
TEMP,
TEMP1,
BODY,
TOTALGROUP,
MARK,
TYPE_SEQ,
PROMOTER,
TABLENO,
MEMBER,
TOURGROUP,
TRDATETIME,
TIME,
BOMNO,
COMMENT,
DEFECTIVE,
M_CHARGE3,
M_CHARGE4,
M_CHARGE5,
M_CHARGE6,
M_CHARGE7,
MC3_BIL,
MC4_BIL,
MC5_BIL,
MC6_BIL,
MC7_BIL,
taxincl,
LOC_CURRRATE,
LOC_CURRCODE,
TITLE_ID,
TITLE_DESP,
consignment,
FOC,
voucherno,
asvoucher,
BOMCOSTMETHOD,

milcert,
importpermit,
PHOTO,
PONO
)
VALUES
(
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.TYPE#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.REFNO#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.REFNO2#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.TRANCODE#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.CUSTNO#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.FPERIOD#">,
<cfqueryparam cfsqltype="cf_sql_date" value="#getictran.WOS_DATE#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.CURRRATE#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.ITEMCOUNT#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.LINECODE#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.ITEMNO#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.DESP#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.DESPA#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.AGENNO#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.LOCATION#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.SOURCE#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.JOB#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.SIGN#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.QTY_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.PRICE_BIL#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.UNIT_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.AMT1_BIL#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.DISPEC1#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.DISPEC2#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.DISPEC3#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.DISAMT_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.AMT_BIL#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.TAXPEC1#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.TAXPEC2#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.TAXPEC3#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.TAXAMT_BIL#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.NOTE_A#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.IMPSTAGE#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.QTY#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.PRICE#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.UNIT#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.AMT1#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.DISAMT#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.AMT#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.TAXAMT#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.FACTOR1#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.FACTOR2#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.DONO#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.BREM1#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.BREM2#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.BREM3#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.BREM4#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.PACKING#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.NOTE1#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.NOTE2#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.GLTRADAC#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.UPDCOST#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.GST_ITEM#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.TOTALUP#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.WITHSN#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.NODISPLAY#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.GRADE#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.PUR_PRICE#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.QTY1#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.QTY2#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.QTY3#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.QTY4#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.QTY5#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.QTY6#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.QTY7#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.QTY_RET#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.TEMPFIGI#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.SERCOST#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.M_CHARGE1#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.M_CHARGE2#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.ADTCOST1#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.ADTCOST2#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.IT_COS#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.AV_COST#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.BATCHCODE#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.POINT#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.INV_DISC#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.INV_TAX#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.SUPP#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.EDI_COU1#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.WRITEOFF#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.TOSHIP#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.SHIPPED#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.NAME#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.DEL_BY#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.VAN#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.GENERATED#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.UD_QTY#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.TOINV#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.EXPORTED#">,

<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.EXPORTED2#">,

<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.BRK_TO#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.SV_PART#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.LAST_YEAR#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.VOID#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.SONO#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.MC1_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.MC2_BIL#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.USERID#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.DAMT#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.OLDBILL#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.WOS_GROUP#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.CATEGORY#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.AREA#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.SHELF#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.TEMP#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.TEMP1#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.BODY#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.TOTALGROUP#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.MARK#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.TYPE_SEQ#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.PROMOTER#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.TABLENO#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.MEMBER#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.TOURGROUP#">,
<cfqueryparam cfsqltype="cf_sql_timestamp" value="#getictran.TRDATETIME#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.TIME#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.BOMNO#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.COMMENT#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.DEFECTIVE#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.M_CHARGE3#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.M_CHARGE4#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.M_CHARGE5#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.M_CHARGE6#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.M_CHARGE7#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.MC3_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.MC4_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.MC5_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.MC6_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.MC7_BIL#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.taxincl#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#getictran.LOC_CURRRATE#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.LOC_CURRCODE#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.TITLE_ID#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.TITLE_DESP#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.consignment#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.FOC#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.voucherno#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.asvoucher#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.BOMCOSTMETHOD#">,

<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.milcert#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.importpermit#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.PHOTO#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.PONO#">
)
</cfquery>
</cfloop>

<cfquery name="getictran" datasource="#dtssync#">
INSERT INTO locationbalpro (refno,type)
VALUES
(<cfqueryparam cfsqltype="cf_sql_varchar" value="#getownlist.refno#">,"#getownlist.type#")
</cfquery>
</cfloop>

</cfloop>
