<cfprocessingdirective pageencoding="UTF-8">
<cfsetting enablecfoutputonly="true">
<cfsetting showdebugoutput="false">

<!---
  Streams an Excel workbook generated by the AI Business Analyst Node service.
  Requires a short-lived token from a prior /chat response (data.export.token).
--->

<cfset AI_NODE_EXPORT_URL = "http://127.0.0.1:8088/export/excel">
<cfset AI_SHARED_SECRET = "cleRkQqi7ogrKX5mAn6xr8LXmz9MobDlzcnKAYYHYCIqDnBy2c5bfuWRyrXDTcVw">
<cfset AI_ALLOWED_ROLES = "super,admin">

<cfif NOT isDefined("session.isLogIn") OR session.isLogIn NEQ "Yes">
    <cfheader statuscode="401">
    <cfcontent type="text/plain" reset="true">Not logged in</cfcontent>
    <cfabort>
</cfif>

<cfif NOT isDefined("husergrpid") OR NOT listFindNoCase(AI_ALLOWED_ROLES, husergrpid)>
    <cfheader statuscode="403">
    <cfcontent type="text/plain" reset="true">Access denied</cfcontent>
    <cfabort>
</cfif>

<cfset exportToken = "">
<cfif isDefined("url.token")>
    <cfset exportToken = trim(toString(url.token))>
</cfif>
<cfif NOT len(exportToken) OR len(exportToken) GT 128>
    <cfheader statuscode="400">
    <cfcontent type="text/plain" reset="true">Invalid export token</cfcontent>
    <cfabort>
</cfif>

<cfset reqUser = "">
<cfif isDefined("HUserID")><cfset reqUser = toString(HUserID)></cfif>
<cfset reqRole = "">
<cfif isDefined("husergrpid")><cfset reqRole = toString(husergrpid)></cfif>

<cfset nodeUrl = AI_NODE_EXPORT_URL
    & "?token=" & encodeForURL(exportToken)
    & "&user=" & encodeForURL(reqUser)
    & "&role=" & encodeForURL(reqRole)>

<cfset dlFilename = "AI_Analyst_export.xlsx">
<cfset httpStatus = 502>
<cfset fileBytes = "">

<cftry>
    <cfhttp url="#nodeUrl#" method="GET" timeout="120" result="aiResp" getAsBinary="yes">
        <cfhttpparam type="header" name="X-AI-Secret" value="#AI_SHARED_SECRET#">
    </cfhttp>

    <cfif structKeyExists(aiResp, "Statuscode")>
        <cfset codePart = listFirst(aiResp.Statuscode, " ")>
        <cfif isNumeric(codePart)>
            <cfset httpStatus = int(codePart)>
        </cfif>
    </cfif>

    <cfif httpStatus EQ 200 AND structKeyExists(aiResp, "FileContent")>
        <cfset fileBytes = aiResp.FileContent>
        <cfif structKeyExists(aiResp, "ResponseHeader") AND isStruct(aiResp.ResponseHeader)>
            <cfif structKeyExists(aiResp.ResponseHeader, "Content-Disposition")>
                <cfset cd = toString(aiResp.ResponseHeader["Content-Disposition"])>
                <cfif findNoCase("filename=", cd)>
                    <cfset fnPart = listLast(cd, "=")>
                    <cfset fnPart = replace(fnPart, """", "", "all")>
                    <cfset fnPart = replace(fnPart, "'", "", "all")>
                    <cfif len(trim(fnPart))><cfset dlFilename = trim(fnPart)></cfif>
                </cfif>
            </cfif>
        </cfif>
    </cfif>

    <cfcatch type="any">
        <cfset httpStatus = 502>
    </cfcatch>
</cftry>

<cfif httpStatus NEQ 200 OR NOT len(fileBytes)>
    <cfheader statuscode="#httpStatus#">
    <cfcontent type="text/plain" reset="true">Export failed or expired. Ask the analyst again and download within 20 minutes.</cfcontent>
    <cfabort>
</cfif>

<cfheader name="Cache-Control" value="no-store">
<cfheader name="Content-Disposition" value='attachment; filename="#dlFilename#"'>
<cfcontent type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" variable="#fileBytes#" reset="true">
